services:
  database:
    container_name: ${CONTAINER_NAME}-database
    image: mysql:9.4.0
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${DATABASE_ROOT_PASSWORD}"]
      timeout: 30s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - internal
  
  wordpress:
    depends_on: 
      - database
    container_name: ${CONTAINER_NAME}-wordpress
    image: wordpress:6.8.3-fpm-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: ${DATABASE_NAME}
      WORDPRESS_DB_USER: ${DATABASE_USER}
      WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - wordpress:/var/www/html
      - ./src/:/var/www/html/wp-content:rw
    networks:
      - internal

  wpcli:
    depends_on:
      - wordpress
      - database
    container_name: ${CONTAINER_NAME}-wpcli
    image: wordpress:cli
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: ${DATABASE_NAME}
      WORDPRESS_DB_USER: ${DATABASE_USER}
      WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - wordpress:/var/www/html
      - ./src:/var/www/html/wp-content
      - ./scripts:/scripts
    networks:
      - internal
    entrypoint: ["/scripts/run-wp-tasks.sh"]

  nginx:
    depends_on:
      - wordpress
    container_name: ${CONTAINER_NAME}-nginx
    image: nginx:1.29.2-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      - SERVER_NAME=${SERVER_NAME}
    ports:
      - "${HTTP_PORT:-8000}:80"
    volumes:
      - ./nginx:/etc/nginx/templates:ro
      - wordpress:/var/www/html
      - ./src/:/var/www/html/wp-content:rw
    networks:
      - internal

  phpmyadmin:
    depends_on:
      - database
    container_name: ${CONTAINER_NAME}-phpmyadmin
    image: phpmyadmin:5.2.3
    restart: unless-stopped
    env_file: .env
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
    ports:
      - "${PHPMYADMIN_PORT:-8001}:80"
    networks:
      - internal

volumes:
  dbdata:
  wordpress:

networks:
  internal:
    driver: bridge