services:
  database:
    # maybe smaller image
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    deploy:
      resources:
        limits:
          memory: 512M

  wordpress:
    environment:
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_ENVIRONMENT_TYPE', 'production');
        define('DISALLOW_FILE_EDIT', true);
        define('DISALLOW_FILE_MODS', true);
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          memory: 256M

  nginx:
    ports:
      - "80:80" #
      - "443:443"
    volumes:
      - ./nginx/prod.conf.template:/etc/nginx/templates/default.conf.template:ro
    deploy:
      resources:
        limits:
          memory: 64M

  wp-init:
    restart: "no"
    volumes:
      - wordpress:/var/www/html
      - ./scripts:/scripts:ro
    entrypoint: ["/scripts/wp-init/entrypoint.sh"]

  db-backup:
    restart: unless-stopped
    volumes:
      - db_backups:/backups
      - ./scripts:/scripts:ro
    entrypoint: ["/scripts/db-backup/entrypoint.sh"]

volumes:
  db_backups:
